# Generated by Django 4.1.3 on 2022-11-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit',
            old_name='amount',
            new_name='paid_amount',
        ),
    ]
