# Generated by Django 4.1.3 on 2022-11-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0002_rename_amount_profit_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profitdone',
            old_name='amount',
            new_name='paid_amount',
        ),
        migrations.AddField(
            model_name='profit',
            name='profit_done',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profit.profitdone'),
        ),
    ]
