# Generated by Django 4.1.3 on 2022-11-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0003_rename_amount_profitdone_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitdone',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Profit',
        ),
        migrations.DeleteModel(
            name='ProfitDone',
        ),
    ]
