# Generated by Django 4.1.3 on 2022-11-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0006_remove_profit_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profit',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='profit',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='profitdone',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='profitdone',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
