# Generated by Django 4.1.3 on 2022-11-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_rename_refunt_amount_revenueseller_refund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueadmin',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='revenueadmin',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='revenueseller',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='revenueseller',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
