# Generated by Django 4.1.3 on 2022-11-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0003_alter_revenueadmin_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueadmin',
            name='used_point_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='revenueadmin',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='revenueadmin',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='revenueseller',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='revenueseller',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
