# Generated by Django 4.1.2 on 2022-10-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='ordered_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
