# Generated by Django 4.1.3 on 2022-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_is_cancelled_orderitem_is_refund_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
